PROFILES:
  - name: <your-name>
    type: zosmf
    hostname: <your_host>
    port: 443
    protocol: https
    encoding: IBM-1047
    rejectunauthorized: false
    userid: <userid>
    password: <password>
URLS:
  - type: jobs
    url: /zosmf/restjobs/jobs
  - type: mfs
    url: /zosmf/restfiles/mfs
DEFAULTS:
  - type: <type>
    name: <your_name>
    